name = "Enigmatica6Expert"
author = "EnigmaticaModpacks"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e974e0785010f5f53a5dff1afa90c57b23169e04e47ab01ffc978f333b3d83b"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
